---
- name: Playbook to create kube.vip config file
  become: true
  hosts:  "{{ target_host }}"
  become_user: root # Ensure root is the user
  tasks:
  - name: Run a command using VIP
    shell: | 
      export VIP=192.168.0.121
      export INTERFACE=ens192
      KVVERSION=$(curl -sL https://api.github.com/repos/kube-vip/kube-vip/releases | jq -r ".[0].name")
      alias kube-vip="ctr image pull ghcr.io/kube-vip/kube-vip:$KVVERSION; ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:$KVVERSION vip /kube-vip"
      kube-vip manifest pod \
          --interface $INTERFACE \
          --address $VIP \
          --controlplane \
          --services \
          --arp \
          --leaderElection | tee /etc/kubernetes/manifests/kube-vip.yaml
     # sed -i 's#path: /etc/kubernetes/admin.conf#path: /etc/kubernetes/super-admin.conf#' \
         # /etc/kubernetes/manifests/kube-vip.yaml
