- name: Create a blank VM
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create new VM
      vmware_guest:
        hostname: 192.168.0.14
        username: administrator@vsphere.local
        password: Q66tp4xe!
        validate_certs: false
        name: K8SCTRL03
        guest_id: "ubuntu64Guest"
        template: ubuntu-noble-24.04-cloud-ansible
        hardware:
          memory_mb: 4096
          num_cpus: 1
          scsi: paravirtual
        networks:
          - name: "VM Network"
            device_name: vmxnet3
        folder: "Discovered virtual machine"
        #cluster: EG-Cluster
        esxi_hostname: vmhost03.home
        datacenter: Arakis
        datastore: vmost03_DS
        state: present
        wait_for_ip_address: yes  # Change this to 'yes' to get the IP address
    - name: Run shell command to extract the IP address
      shell: ip a | awk '/inet / && !/127.0.0.1/ {print $2}' | cut -d'/' -f1
      register: ip_output

    - name: Set IP address as a variable
      set_fact:
        vm_ip: "{{ ip_output.stdout }}"
      

- name: Configure static IP on the newly created VM
  hosts: "{{ vm_ip }}"
  become: yes
  gather_facts: yes
  tasks:
    - name: Configure static IP in netplan
      copy:
        dest: /etc/netplan/50-cloud-init.yaml
        content: |
          network:
            version: 2
            ethernets:
              ens192:  # Replace with your network interface name if necessary
                dhcp4: no
                addresses:
                - 192.168.0.103/24  # Replace with your desired static IP and subnet
                nameservers:
                  addresses:
                  - 192.168.0.15  # Replace with your DNS server(s)
                  - 192.168.0.8
                routes:
                - to: default
                  via: 192.168.0.1
    - name: Apply netplan configuration
      command: netplan apply

